---
- name: Install Docker on multiple machines
  hosts: all
  become: true
  tasks:
    - name: Update and install prerequisites
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Update and install prerequisites
      ansible.builtin.apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | apt-key add -
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/centos/gpg | gpg --dearmor -o /etc/pki/rpm-gpg/docker
      when: ansible_os_family == "RedHat"

    - name: Add Docker repository
      ansible.builtin.shell: |
        add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} \
        $(lsb_release -cs) stable"
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      ansible.builtin.shell: |
        yum-config-manager \
        --add-repo \
        https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_os_family == "RedHat"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add current user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
